# Generated by Django 4.2.3 on 2023-07-23 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0003_directorgeneral_especialidad_laboratorio_ciudad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directorgeneral',
            name='especialidad',
            field=models.CharField(default='Medicina general', max_length=100),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='ciudad',
            field=models.CharField(default='Concepcion', max_length=100),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='pais',
            field=models.CharField(default='Chile', max_length=100),
        ),
    ]
